In [2]:
import numpy as np
import scipy as sp 
import pandas as pd
import h5py as h5py
import math

In [8]:
from Q4 import *

In [9]:
def load_dataset(dataset = 0):

    """ Returns the shuffled dataset from the .h5 file and calculates the class frequences. 

    Parameters
    ----------
    dataset : Integer to denoted the type of dataset to be loaded, default = 0

    Returns
    --------
    X :  2-dimensional numpy array of shape (n_samples, n_features) which acts as data.
    Y : 1-dimensional numpy array of shape (n_samples,) which acts as labels.

    """
    ## Dataset A
    if (dataset == 0):
        hf = h5py.File('Dataset/part_A_train.h5', 'r') #read the dataset 
        
        X = np.array(hf['X']) # X data  
        Y = np.array(hf['Y']) # class labels of the form [0,0,0,1,0,,..]
        print(X.shape,Y.shape)

        """ To calculate the class frequencies """

        print("The class frequencies are : ")

        for i in range(Y.shape[1]):
            freq = np.sum(Y[:,i])
            print("The frequency of class " + str(i) + " is " + str(freq) + " / " + str(Y.shape[0]) )

        """ Converting the binary class labels into single valued blabels """
        y = []
        for i in range(Y.shape[0]):
            for j in range(Y.shape[1]):
                if(Y[i,j] == 1):
                    y.append(j)
        
        y = np.array(y)
        Y = y.reshape(-1,1)
        Y = np.squeeze(Y)

        """ Shuffling the dataset """
        np.random.seed(123)
        index = np.random.permutation(X.shape[0])
        np.take(X, index, axis = 0, out = X)
        np.take(Y, index, axis = 0, out = Y)

    ## dataset B
    elif(dataset == 1):

        hf = h5py.File('Dataset/part_B_train.h5', 'r') #read the dataset 

        X = np.array(hf['X']) # X data  
        Y = np.array(hf['Y']) # class labels of the form [0,0,0,1,0,,..]
        print(X.shape,Y.shape)

        """ To calculate the class frequencies """

        print("The class frequencies are : ")

        for i in range(Y.shape[1]):
            freq = np.sum(Y[:,i])
            print("The frequency of class " + str(i) + " is " + str(freq) + " / " + str(Y.shape[0]) )

        """ Converting the binary class labels into single valued blabels """
        y = []
        for i in range(Y.shape[0]):
            for j in range(Y.shape[1]):
                if(Y[i,j] == 1):
                    y.append(j)

        y = np.array(y)
        Y = y.reshape(-1,1)
        Y = np.squeeze(Y)

        """ Shuffling the dataset """
        np.random.seed(123)
        index = np.random.permutation(X.shape[0])
        np.take(X, index, axis = 0, out = X)
        np.take(Y, index, axis = 0, out = Y)

    return X,Y

In [21]:
X,y = load_dataset(1)
print(y)

(4200, 2048) (4200, 2)
The class frequencies are : 
The frequency of class 0 is 2097 / 4200
The frequency of class 1 is 2103 / 4200
[1 0 0 ... 0 0 1]


In [22]:
print(X[1])

[ 49  67  67 ... 168  85 102]


In [23]:
nb = MyGaussianNaiveBayes()
nb.fit(X,y)

In [26]:
y_pred = nb.predict(X)
# print(y_pred)
# print(y)

Total samples done :  0
Total samples done :  10
Total samples done :  20
Total samples done :  30
Total samples done :  40
Total samples done :  50
Total samples done :  60
Total samples done :  70
Total samples done :  80
Total samples done :  90
Total samples done :  100
Total samples done :  110
Total samples done :  120
Total samples done :  130
Total samples done :  140
Total samples done :  150
Total samples done :  160
Total samples done :  170
Total samples done :  180
Total samples done :  190
Total samples done :  200
Total samples done :  210
Total samples done :  220
Total samples done :  230
Total samples done :  240
Total samples done :  250
Total samples done :  260
Total samples done :  270
Total samples done :  280
Total samples done :  290
Total samples done :  300
Total samples done :  310
Total samples done :  320
Total samples done :  330
Total samples done :  340
Total samples done :  350
Total samples done :  360
Total samples done :  370
Total samples done :  3

Total samples done :  3080
Total samples done :  3090
Total samples done :  3100
Total samples done :  3110
Total samples done :  3120
Total samples done :  3130
Total samples done :  3140
Total samples done :  3150
Total samples done :  3160
Total samples done :  3170
Total samples done :  3180
Total samples done :  3190
Total samples done :  3200
Total samples done :  3210
Total samples done :  3220
Total samples done :  3230
Total samples done :  3240
Total samples done :  3250
Total samples done :  3260
Total samples done :  3270
Total samples done :  3280
Total samples done :  3290
Total samples done :  3300
Total samples done :  3310
Total samples done :  3320
Total samples done :  3330
Total samples done :  3340
Total samples done :  3350
Total samples done :  3360
Total samples done :  3370
Total samples done :  3380
Total samples done :  3390
Total samples done :  3400
Total samples done :  3410
Total samples done :  3420
Total samples done :  3430
Total samples done :  3440
T

In [31]:
# print(y_pred)
# print(y)
c = 0
for i in range(len(y)):
    if(y[i] == y_pred[i]):
        c+=1
print(c/len(y))

0.5721428571428572


In [32]:
from sklearn.naive_bayes import GaussianNB

In [33]:
gnb = GaussianNB()
y_pred = gnb.fit(X, y).predict(X)

In [34]:
print(y_pred)
print(y)
c = 0
for i in range(len(y)):
    if(y[i] == y_pred[i]):
        c+=1
print(c/len(y))

[0 0 0 ... 0 1 1]
[1 0 0 ... 0 0 1]
0.5721428571428572
