In [1]:
import numpy as np
import pandas as pd
from scratch import *

Linear Regression
Training loss after  0  iterations is  1.5811388300841898
Training loss after  500  iterations is  0.11515089871796896
Training loss after  1000  iterations is  0.11515089872154656
Training loss after  1500  iterations is  0.11515089872154524
Training loss after  2000  iterations is  0.11515089872154423
Training loss after  2500  iterations is  0.11515089872154423
Training loss after  3000  iterations is  0.11515089872154423
Training loss after  3500  iterations is  0.11515089872154423
Training loss after  4000  iterations is  0.11515089872154423
Training loss after  4500  iterations is  0.11515089872154423
Predicted Values: [[2.76462962]
 [2.76462962]]
True Values: [3]
[1.5811388300841898, 1.3517062465607521, 1.1226091064098265, 0.8940885829444581, 0.666689680276224, 0.44195678091711044, 0.22658494162040946, 0.09144726050688341, 0.08933636784182054, 0.08737238529854577, 0.08584171929834634, 0.08561251056962607, 0.0889605289204263, 0.09889558761801534, 0.1107993211469

In [2]:
preprocess = MyPreProcessor()
X,Y=preprocess.pre_process(2)
print(X)
print(Y)

[[ 0.87839635  0.63786234  0.04636691  0.00214328]
 [-0.3591203   0.24024586 -0.67295314 -0.33710931]
 [ 0.623677   -1.18177509  0.7229981  -0.22269672]
 ...
 [ 1.06546255 -0.15930343 -0.07456904  0.11257781]
 [ 1.01899251  1.65197176 -0.70770485 -0.3542859 ]
 [-1.18777658  1.28775488 -0.01623361 -1.44873463]]
[[0]
 [1]
 [0]
 ...
 [0]
 [0]
 [1]]


In [3]:
X_train = X[0:1000, :]
X_test = X[1000:, :]
y_train = Y[0:1000,:]
y_test = Y[1000:,:]
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1000, 4)
(372, 4)
(1000, 1)
(372, 1)


In [4]:
log_regressor = MyLogisticRegression()
log_regressor.fit(X_train, y_train, X_test, y_test, epochs = 10000 ,learning_rate = 0.005)

Training loss after  0  iterations is :  0.6931471805599454  | validation loss is :  0.6931471805599454
Training accuracy after  0  iterations is :  43.1 %  | validation accuracy is :  48.11827956989247 %
Training loss after  500  iterations is :  0.49113111891612016  | validation loss is :  0.514453101011192
Training accuracy after  500  iterations is :  78.5 %  | validation accuracy is :  73.65591397849462 %
Training loss after  1000  iterations is :  0.4086300699562395  | validation loss is :  0.43440163044486385
Training accuracy after  1000  iterations is :  88.1 %  | validation accuracy is :  84.40860215053763 %
Training loss after  1500  iterations is :  0.35225687218775215  | validation loss is :  0.37708211196920505
Training accuracy after  1500  iterations is :  92.60000000000001 %  | validation accuracy is :  88.97849462365592 %
Training loss after  2000  iterations is :  0.3105629854367549  | validation loss is :  0.33390304656722886
Training accuracy after  2000  iteration