In [556]:
from Q1 import *
import pandas as pd
import copy

In [399]:
# n_layers, layer_sizes, activation, learning_rate, weight_init, batch_size, num_epochs


In [400]:
df = pd.read_csv("dataset/mnist/mnist_train.csv")

In [401]:
df.head

<bound method NDFrame.head of        label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28

In [402]:
dataset = np.array(df)

In [403]:
y = dataset[:, 0]
X = dataset[:, 1:]

In [404]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [405]:
y.shape


(60000,)

In [406]:
nn = MyNeuralNetwork(5,[8,16,8,4], "relu", 0.01, "normal", 0,0)

In [407]:
a = nn.expand_labels(y)

In [408]:
a.shape

(10, 60000)

In [409]:
a[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [410]:
np.argmax(a[0])

1

In [411]:
len(y)

60000

In [412]:
m = len(y)
c = np.max(y)
new_y = np.zeros((m,c+1))
for i in range(m):
    l = y[i]
    new_y[i,l] = 1


In [413]:
new_y.shape

(60000, 10)

In [414]:
new_y.T

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [415]:
X = X/255


In [416]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [417]:
y

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [673]:
import numpy as np 
from tqdm import tqdm

class MyNeuralNetwork():
    """
    My implementation of a Neural Network Classifier.
    """

    acti_fns = ['relu', 'sigmoid', 'linear', 'tanh']
    weight_inits = ['zero', 'random', 'normal']

    def __init__(self, n_layers, layer_sizes, activation, learning_rate, weight_init, batch_size, num_epochs):
        """
        Initializing a new MyNeuralNetwork object

        Parameters
        ----------
        n_layers : int value specifying the number of layers

        layer_sizes : integer array of size n_layers specifying the number of nodes in each layer

        activation : string specifying the activation function to be used
                     possible inputs: relu, sigmoid, linear, tanh

        learning_rate : float value specifying the learning rate to be used

        weight_init : string specifying the weight initialization function to be used
                      possible inputs: zero, random, normal

        batch_size : int value specifying the batch size to be used

        num_epochs : int value specifying the number of epochs to be used
        """

        if activation not in self.acti_fns:
            raise Exception('Incorrect Activation Function')

        if weight_init not in self.weight_inits:
            raise Exception('Incorrect Weight Initialization Function')


        self.n_layers = n_layers
        self.layer_sizes = layer_sizes
        self.activation = activation
        self.learning_rate = learning_rate
        self.weight_init = weight_init
        self.batch_size = batch_size
        self.num_epochs = num_epochs


        pass

    def relu(self, X):
        """
        Calculating the ReLU activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
        x_calc = np.maximum(0,X)
        cache = {"Z" : X}

        return np.array(x_calc) , cache

    def relu_grad(self, da, activation_cache):
        """
        Calculating the gradient of ReLU activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
        z = activation_cache["Z"]
        x_calc = np.array(da)
        x_calc[z <= 0] = 0
        return x_calc

    def sigmoid(self, X):
        """
        Calculating the Sigmoid activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """

        x_calc = 1/(1+np.exp(-1*X))
        cache = {"Z" : X}
        return x_calc,cache

    def sigmoid_grad(self, da, activation_cache):
        """
        Calculating the gradient of Sigmoid activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
        z = activation_cache["Z"]
        a = 1/(1+np.exp(-1*z + 10**-7))

        dz = np.multiply(da,a*(1-a))
#         dz = np.add(np.log(da), np.log(a*(1-a)))
        return dz

    def linear(self, X):
        """
        Calculating the Linear activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
        cache = {"Z" : X}
        return X, cache

    def linear_grad(self, da, activation_cache):
        """
        Calculating the gradient of Linear activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
        z = activation_cache["Z"]
        dz = np.array(da)
        return np.array(dz)

    def tanh(self, X):
        """
        Calculating the Tanh activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """

        x_calc = (np.exp(X) - np.exp(-X))/(np.exp(X) + np.exp(-X))

        cache = {"Z" : X}

        return x_calc, cache

    def tanh_grad(self, da, activation_cache):
        """
        Calculating the gradient of Tanh activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
        z = activation_cache["Z"]
        dz = np.multiply(da,1 - np.power(self.tanh(z)[0],2))

        return dz

    def softmax(self, X):
        """
        Calculating the ReLU activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
#         print("Softmax : ", X.shape)
        x_calc = np.exp(X)/(np.sum(np.exp(X), axis = 0) + 10**-6)
#         print("X : ", X)
#         print("x_calc : ", x_calc)
#         print("np.exp(X): ", np.exp(X))
#         print("np.sum(np.exp(X), axis = 0) : ", np.sum(np.exp(X), axis = 0))

            
        cache = {"Z" : X}
        return x_calc, cache

    def softmax_grad(self, da, activation_cache,y):
        """
        Calculating the gradient of Softmax activation for a particular layer

        Parameters
        ----------
        X : 1-dimentional numpy array 

        Returns
        -------
        x_calc : 1-dimensional numpy array after calculating the necessary function over X
        """
        z = activation_cache["Z"]
#         print("da :", da.shape)
#         print("softmax : ", self.softmax(z)[0].shape)
#         print("y : ", y.shape)
#         print()
        dz = np.multiply(da,(self.softmax(z)[0] - y))
#         print("dz : ", dz.shape)
#         dz = np.add(np.log(da), np.log(self.softmax(z)[0] - y))
        return dz

    def zero_init(self, shape):
        """
        Calculating the initial weights after Zero Activation for a particular layer

        Parameters
        ----------
        shape : tuple specifying the shape of the layer for which weights have to be generated 

        Returns
        -------
        weight : 1-dimensional numpy array which contains the initial weights for the requested layer

        """

        weight = np.zeros(shape)
        return weight

    def random_init(self, shape):
        """
        Calculating the initial weights after Random Activation for a particular layer

        Parameters
        ----------
        shape : tuple specifying the shape of the layer for which weights have to be generated 

        Returns
        -------
        weight : 1-dimensional numpy array which contains the initial weights for the requested layer
        """
        weight = np.random.rand(shape[0], shape[1])*0.01
        return weight

    def normal_init(self, shape):
        """
        Calculating the initial weights after Normal(0,1) Activation for a particular layer

        Parameters
        ----------
        shape : tuple specifying the shape of the layer for which weights have to be generated 

        Returns
        -------
        weight : 1-dimensional numpy array which contains the initial weights for the requested layer
        """
        weight = np.random.normal(scale = 0.01,size = shape)
        return weight

    def fit(self, X, y, X_test = None, y_test = None):
        """
        Fitting (training) the linear model.

        Parameters
        ----------
        X : 2-dimensional numpy array of shape (n_samples, n_features) which acts as training data.

        y : 1-dimensional numpy array of shape (n_samples,) which acts as training labels.
        
        Returns
        -------
        self : an instance of self
        """

        # fit function has to return an instance of itself or else it won't work with test.py
        X = X.T
        y = self.expand_labels(y)
        
        n_0 , m = X.shape
        n_l = y.shape[0]

        parameters = self.initialization(n_0,n_l)
        self.parameters = parameters

        train_loss_history = []
        train_accuracy_history = []
        test_loss_history = []
        test_accuracy_history = []

        

        for epoch in tqdm(range(self.num_epochs), desc = "Progress Total : ", position = 0, leave = True):


            n_batches = m//self.batch_size
            X_batches = [X[:,self.batch_size*i:self.batch_size*(i+1)] for i in range(0,n_batches)]
            y_batches = [y[:,self.batch_size*i:self.batch_size*(i+1)] for i in range(0,n_batches)]

            train_batch_loss = []
            test_batch_loss = []
            train_batch_accuracy = []
            test_batch_accuracy = []

            for curr_x, curr_y in tqdm(zip(X_batches,y_batches), desc = "Progress Epoch: " + str(epoch+1) + "/" + str(self.num_epochs), position = 0, leave = True, total = len(X_batches)):
                A, cache = self.forward_prop(curr_x,parameters)
#                 print("A_l : " , A)

                train_cost = self.compute_cost(A,curr_y)
                train_batch_loss.append(train_cost)

                gradients = self.backward_prop(curr_y,A,cache)
                
                
#                 for key in list(gradients.keys()):
#                     gradients[key] = np.maximum(np.minimum(gradients[key],10), -10)

                parameters = self.update_parameters(parameters,gradients, self.learning_rate)


                self.parameters = parameters
#                 self.backwardPhase(curr_x.T, curr_y.T, A.T, cache)
                
#                 print(gradients)
                
#             print(parameters)
            print("Training Loss : ", np.array(train_batch_loss).mean())


            # if(X_test is not None):

        self.parameters = parameters





        return self

    def predict_proba(self, X):
        """
        Predicting probabilities using the trained linear model.

        Parameters
        ----------
        X : 2-dimensional numpy array of shape (n_samples, n_features) which acts as testing data.

        Returns
        -------
        y : 1-dimensional numpy array of shape (n_samples,) which contains the prediction probabilities.
        """

        # return the numpy array y which contains the predicted values
        proba,_ = self.forward_prop(X,self.parameters)
        return proba

    def predict(self, X):
        """
        Predicting values using the trained linear model.

        Parameters
        ----------
        X : 2-dimensional numpy array of shape (n_samples, n_features) which acts as testing data.

        Returns
        -------
        y : 1-dimensional numpy array of shape (n_samples,) which contains the predicted values.
        """

        # return the numpy array y which contains the predicted values


        A_l, cache = self.forward_prop(X.T,self.parameters)
        predict = np.argmax(A_l, axis = 0)

        return predict

    def score(self, X, y):
        """
        Predicting values using the trained linear model.

        Parameters
        ----------
        X : 2-dimensional numpy array of shape (n_samples, n_features) which acts as testing data.

        y : 1-dimensional numpy array of shape (n_samples,) which acts as testing labels.

        Returns
        -------
        acc : float value specifying the accuracy of the model on the provided testing set
        """

        # return the numpy array y which contains the predicted values
        
        cur = 0
        y_pred = self.predict(X.T)
        for i in range(len(y_pred)):
            if(y[i] == y_pred[i]):
                cur+=1
        return cur/len(y_pred)

    def initialization(self, n_0, n_l):
        """

        Initializes the model parameters of the deep neural network

        Parameters 
        -----------
        n_0 : int signifying the number of nodes in the input layer (n_features)
        n_l : int signifying the number of output nodes.

        Returns
        -------
        Paramsters : Model parameters 

        """

        parameters = {}
        layers = self.layer_sizes
        layers.insert(0,n_0)
        layers.append(n_l)


        for i in range(1,len(layers)):
            if(self.weight_init == 'zero'):
                curr_layer = self.zero_init((layers[i],layers[i-1]))

            elif(self.weight_init == 'random'):
                curr_layer = self.random_init((layers[i],layers[i-1]))

            else:
                curr_layer = self.normal_init((layers[i],layers[i-1]))

            parameters["W" + str(i)] = curr_layer
            parameters["b" + str(i)] = np.zeros((layers[i],1))

        self.parameters = parameters

        return parameters


    def forward_prop(self,X,parameters):

        """
        Implements one forward propagation of the deep neural network.

        Parameters 
        ----------
        X : Training set to be forward propagated
        parameters : model parameters 

        Returns
        -------
        A_l : Activations of the final layer
        forward_cache : list contraining all the linear_cache and activation_cache of all the layers

        """

        A = X
        L = len(parameters)//2

        forward_cache  = []
#         activations = []

        for i in range(1,L):
            A_prev = A
            Z = np.dot(parameters["W" + str(i)],A_prev) + parameters["b" + str(i)]
            linear_cache = (A_prev, parameters["W" + str(i)], parameters["b" + str(i)])

            if(self.activation == "relu"):
                A, activation_cache = self.relu(Z)

            elif (self.activation == "tanh"):
                A, activation_cache = self.tanh(Z)

            elif (self.activation == "linear"):
                A, activation_cache = self.linear(Z)

            elif (self.activation == "sigmoid"):
                A, activation_cache = self.sigmoid(Z)

            layer_cache = (linear_cache, activation_cache)

            forward_cache.append(layer_cache)
#             activations.append(A)           
            A_prev = A
        
        
        Z_l = np.dot(parameters["W" + str(L)],A_prev) + parameters["b" + str(L)]
        linear_cache = (A_prev, parameters["W" + str(L)], parameters["b" + str(L)])
        
        A_l, activation_cache = self.softmax(Z_l)
        layer_cache = (linear_cache, activation_cache)
        forward_cache.append(layer_cache)
#         activation.append(A_l)

        return A_l, forward_cache



    def compute_cost(self,A,y):

        """
        Computes the cross-entropy loss.

        Parameters
        ----------
        A : Activations of the final layer of the model
        y : ground truth labels of the training batch

        Returns
        -------
        cost : calculated cost

        """


        m = y.shape[1]

        cost = (-1 / m) * np.sum(np.multiply(y, np.log(A + 10**-7)) + np.multiply(1 - y, np.log(1 - A - 10**-7)))
#         print(np.multiply(y, np.log(A)) + np.multiply(1 - y, np.log(1 - A)))

        cost = np.squeeze(cost)

        return cost



    def backward_prop(self, y, A_l,cache):
        """
        Implements backward propagation of the complete model.

        Parameters
        ----------
        y : The ground truth labels of the curr training set
        A_l : activations of the final layer of the model
        cache : tuple containing the linear_cache and activation_cache

        Returns
        -------
        gradients : Dictionary containing the gradient vectors for each layer of the model

        """
        """
        dL / dw = dL/d(a_l) * d(a_l)/d(z_l)
        
        
        
        """
        gradients  = {}
        L = len(cache)

#         da_l = -1*np.divide(y,A_l) + np.divide(1-y, 1 - A_l)
#         print(da_l.shape)
        
        da_l = (A_l - y)/y.shape[1]
        linear_cache, activation_cache = cache[L-1]

#         dz_l = self.sigmoid_grad(da_l, activation_cache)
        gradients["dW" + str(L)], gradients["db" + str(L)], gradients["dA" + str(L)] = self.one_step_backward(da_l,linear_cache)


        for i in range(L-1,0,-1):
            linear_cache, activation_cache = cache[i-1]

            if(self.activation == "relu"):
                dz = self.relu_grad(gradients["dA" + str(i+1)], activation_cache)
                gradients["dW" + str(i)], gradients["db" + str(i)], gradients["dA" + str(i)] = self.one_step_backward(dz,linear_cache)

            elif (self.activation == "tanh"):
                dz = self.tanh_grad(gradients["dA" + str(i+1)], activation_cache)
                gradients["dW" + str(i)], gradients["db" + str(i)], gradients["dA" + str(i)] = self.one_step_backward(dz,linear_cache)

            elif (self.activation == "linear"):
                dz = self.linear_grad(gradients["dA" + str(i+1)], activation_cache)
                gradients["dW" + str(i)], gradients["db" + str(i)], gradients["dA" + str(i)] = self.one_step_backward(dz,linear_cache)

            elif (self.activation == "sigmoid"):
                dz = self.sigmoid_grad(gradients["dA" + str(i+1)], activation_cache)
                gradients["dW" + str(i)], gradients["db" + str(i)], gradients["dA" + str(i)] = self.one_step_backward(dz,linear_cache)
        
        
        
        
        return gradients


    def one_step_backward(self,dz, linear_cache):

        """
        Performs one step backward propagationm

        Parameters 
        ----------
        dz : The gradient of the loss with respoct to z 
        linear_cache : tuple containing the preactivated a,w,b for the layer

        Returns
        --------
        dw : The gradient of the loss with respoct to w
        db : The gradient of the loss with respoct to b 
        da_prev : The gradient of the loss with respoct to a_prev


        """

        
        A_prev, W, b = linear_cache
        m = A_prev.shape[1]

        dw = (1/m)*(np.dot(dz, A_prev.T))
        db = (1/m)*(np.sum(dz, axis=1, keepdims = True))
        da_prev = np.dot(W.T,dz)
        

        return dw,db,da_prev
    


    def update_parameters(self, parameters, gradients, learning_rate):
        """
        Update the model parameters. 

        Parameters
        ----------

        parameters : dictionary containing the model parameters.
        gradients : dictionary contrainig the gradients for each layer.
        learning_rate : learning rate of the model.

        Returns
        --------
        parameters : updated paramteters 


        """



        L = len(parameters) //2

        for i in range(0, L):
#             print(gradients["dW" + str(i+1)])
#                 print("dgdgdgdgd")
            parameters["W" + str(i+1)] = parameters["W" + str(i+1)] -learning_rate*gradients["dW" + str(i+1)]
            parameters["b" + str(i+1)] = parameters["b" + str(i+1)] -learning_rate*gradients["db" + str(i+1)]

        self.parameters = copy.deepcopy(parameters)

        return self.parameters



    def expand_labels(self, y):

        m = len(y)
        c = np.max(y)
        new_y = np.zeros((m,c+1))
        for i in range(m):
            l = y[i]
            new_y[i,l] = 1

        return new_y.T





In [674]:
mynn = MyNeuralNetwork(3,[256,128,64], "sigmoid", 0.01, "normal", 5000, 20)

In [675]:
y = y.reshape(-1,1)

In [676]:
# X[1]

In [677]:
mynn.fit(X,y)

Progress Epoch: 1/20: 100%|████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.44it/s]


Training Loss :  3.251008260391982


Progress Epoch: 2/20: 100%|████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.48it/s]


Training Loss :  3.251008115942813


Progress Epoch: 3/20: 100%|████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.39it/s]


Training Loss :  3.2510079715054623


Progress Epoch: 4/20: 100%|████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.38it/s]


Training Loss :  3.2510078270799325


Progress Epoch: 5/20: 100%|████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.34it/s]


Training Loss :  3.25100768266622


Progress Epoch: 6/20:  17%|██████████▏                                                  | 2/12 [00:00<00:04,  2.45it/s]


KeyboardInterrupt: 

In [635]:
y_pred = mynn.predict(X)

In [636]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [637]:
y

array([[5],
       [0],
       [4],
       ...,
       [5],
       [6],
       [8]], dtype=int64)

In [638]:
cur = 0
for i in range(len(y_pred)):
    if(y[i] == y_pred[i]):
        cur+=1
print(cur/len(y_pred))

0.11236666666666667


In [ ]:
# mynn.predict_proba(a.T)

In [89]:
import tensorflow as tf

In [101]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(256,input_shape = (784,),activation='relu'),
    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(
    loss='categorical_crossentropy',
    optimizer=tf.keras.optimizers.Adam(0.01),
    metrics=['accuracy'],
)

model.fit(
    X,y_n,
    epochs=100
    
)


Epoch 1/100
1875/1875 [==============================] - ETA: 1s - loss: 2.2946 - accuracy: 0.21 - ETA: 4s - loss: 1.6196 - accuracy: 0.44 - ETA: 4s - loss: 1.2519 - accuracy: 0.56 - ETA: 4s - loss: 1.0754 - accuracy: 0.63 - ETA: 4s - loss: 0.9786 - accuracy: 0.67 - ETA: 4s - loss: 0.8961 - accuracy: 0.70 - ETA: 4s - loss: 0.8331 - accuracy: 0.73 - ETA: 4s - loss: 0.7813 - accuracy: 0.75 - ETA: 4s - loss: 0.7546 - accuracy: 0.76 - ETA: 4s - loss: 0.7203 - accuracy: 0.77 - ETA: 4s - loss: 0.7068 - accuracy: 0.78 - ETA: 4s - loss: 0.6955 - accuracy: 0.78 - ETA: 4s - loss: 0.6778 - accuracy: 0.79 - ETA: 4s - loss: 0.6611 - accuracy: 0.79 - ETA: 4s - loss: 0.6478 - accuracy: 0.80 - ETA: 4s - loss: 0.6316 - accuracy: 0.81 - ETA: 4s - loss: 0.6137 - accuracy: 0.81 - ETA: 4s - loss: 0.5966 - accuracy: 0.82 - ETA: 4s - loss: 0.5873 - accuracy: 0.82 - ETA: 4s - loss: 0.5749 - accuracy: 0.82 - ETA: 4s - loss: 0.5611 - accuracy: 0.83 - ETA: 4s - loss: 0.5516 - accuracy: 0.83 - ETA: 4s - loss: 0.5

1875/1875 [==============================] - ETA: 0s - loss: 0.1840 - accuracy: 0.93 - ETA: 6s - loss: 0.1708 - accuracy: 0.94 - ETA: 6s - loss: 0.1531 - accuracy: 0.95 - ETA: 6s - loss: 0.1670 - accuracy: 0.95 - ETA: 6s - loss: 0.2011 - accuracy: 0.94 - ETA: 6s - loss: 0.2194 - accuracy: 0.94 - ETA: 6s - loss: 0.2198 - accuracy: 0.94 - ETA: 6s - loss: 0.2309 - accuracy: 0.94 - ETA: 5s - loss: 0.2457 - accuracy: 0.94 - ETA: 5s - loss: 0.2656 - accuracy: 0.93 - ETA: 5s - loss: 0.2695 - accuracy: 0.93 - ETA: 5s - loss: 0.2554 - accuracy: 0.93 - ETA: 5s - loss: 0.2536 - accuracy: 0.93 - ETA: 5s - loss: 0.2561 - accuracy: 0.93 - ETA: 5s - loss: 0.2485 - accuracy: 0.93 - ETA: 5s - loss: 0.2569 - accuracy: 0.93 - ETA: 5s - loss: 0.2594 - accuracy: 0.93 - ETA: 4s - loss: 0.2625 - accuracy: 0.93 - ETA: 4s - loss: 0.2568 - accuracy: 0.93 - ETA: 4s - loss: 0.2632 - accuracy: 0.93 - ETA: 4s - loss: 0.2699 - accuracy: 0.93 - ETA: 4s - loss: 0.2695 - accuracy: 0.93 - ETA: 4s - loss: 0.2670 - accura

1875/1875 [==============================] - ETA: 0s - loss: 0.0921 - accuracy: 0.96 - ETA: 6s - loss: 0.1587 - accuracy: 0.95 - ETA: 6s - loss: 0.1905 - accuracy: 0.94 - ETA: 6s - loss: 0.1991 - accuracy: 0.94 - ETA: 6s - loss: 0.1932 - accuracy: 0.95 - ETA: 6s - loss: 0.2103 - accuracy: 0.95 - ETA: 6s - loss: 0.2334 - accuracy: 0.94 - ETA: 5s - loss: 0.2215 - accuracy: 0.94 - ETA: 5s - loss: 0.2147 - accuracy: 0.94 - ETA: 5s - loss: 0.2138 - accuracy: 0.94 - ETA: 5s - loss: 0.2088 - accuracy: 0.94 - ETA: 5s - loss: 0.2041 - accuracy: 0.95 - ETA: 5s - loss: 0.2045 - accuracy: 0.94 - ETA: 5s - loss: 0.2034 - accuracy: 0.95 - ETA: 5s - loss: 0.2033 - accuracy: 0.95 - ETA: 5s - loss: 0.2044 - accuracy: 0.94 - ETA: 5s - loss: 0.2039 - accuracy: 0.94 - ETA: 5s - loss: 0.2056 - accuracy: 0.94 - ETA: 5s - loss: 0.2082 - accuracy: 0.94 - ETA: 5s - loss: 0.2129 - accuracy: 0.94 - ETA: 4s - loss: 0.2127 - accuracy: 0.94 - ETA: 4s - loss: 0.2146 - accuracy: 0.94 - ETA: 4s - loss: 0.2131 - accura

1875/1875 [==============================] - ETA: 0s - loss: 0.1447 - accuracy: 0.93 - ETA: 5s - loss: 0.1701 - accuracy: 0.96 - ETA: 5s - loss: 0.1695 - accuracy: 0.96 - ETA: 5s - loss: 0.1524 - accuracy: 0.96 - ETA: 5s - loss: 0.1684 - accuracy: 0.96 - ETA: 5s - loss: 0.1650 - accuracy: 0.96 - ETA: 5s - loss: 0.1687 - accuracy: 0.96 - ETA: 5s - loss: 0.1661 - accuracy: 0.96 - ETA: 5s - loss: 0.1651 - accuracy: 0.96 - ETA: 5s - loss: 0.1617 - accuracy: 0.96 - ETA: 5s - loss: 0.1575 - accuracy: 0.96 - ETA: 5s - loss: 0.1571 - accuracy: 0.96 - ETA: 5s - loss: 0.1549 - accuracy: 0.96 - ETA: 5s - loss: 0.1574 - accuracy: 0.96 - ETA: 5s - loss: 0.1563 - accuracy: 0.96 - ETA: 5s - loss: 0.1601 - accuracy: 0.96 - ETA: 5s - loss: 0.1590 - accuracy: 0.96 - ETA: 4s - loss: 0.1620 - accuracy: 0.96 - ETA: 4s - loss: 0.1597 - accuracy: 0.96 - ETA: 4s - loss: 0.1630 - accuracy: 0.95 - ETA: 4s - loss: 0.1605 - accuracy: 0.96 - ETA: 4s - loss: 0.1681 - accuracy: 0.96 - ETA: 4s - loss: 0.1688 - accura

1875/1875 [==============================] - ETA: 0s - loss: 0.2161 - accuracy: 0.93 - ETA: 5s - loss: 0.1218 - accuracy: 0.96 - ETA: 5s - loss: 0.1168 - accuracy: 0.96 - ETA: 5s - loss: 0.1370 - accuracy: 0.96 - ETA: 5s - loss: 0.1301 - accuracy: 0.96 - ETA: 5s - loss: 0.1425 - accuracy: 0.96 - ETA: 5s - loss: 0.1473 - accuracy: 0.96 - ETA: 5s - loss: 0.1570 - accuracy: 0.96 - ETA: 5s - loss: 0.1539 - accuracy: 0.96 - ETA: 5s - loss: 0.1529 - accuracy: 0.96 - ETA: 5s - loss: 0.1486 - accuracy: 0.96 - ETA: 5s - loss: 0.1478 - accuracy: 0.96 - ETA: 5s - loss: 0.1471 - accuracy: 0.96 - ETA: 5s - loss: 0.1502 - accuracy: 0.96 - ETA: 5s - loss: 0.1511 - accuracy: 0.96 - ETA: 5s - loss: 0.1545 - accuracy: 0.96 - ETA: 5s - loss: 0.1548 - accuracy: 0.96 - ETA: 5s - loss: 0.1563 - accuracy: 0.96 - ETA: 5s - loss: 0.1566 - accuracy: 0.96 - ETA: 5s - loss: 0.1565 - accuracy: 0.96 - ETA: 5s - loss: 0.1563 - accuracy: 0.96 - ETA: 5s - loss: 0.1565 - accuracy: 0.96 - ETA: 4s - loss: 0.1570 - accura

1875/1875 [==============================] - ETA: 0s - loss: 0.1559 - accuracy: 0.96 - ETA: 6s - loss: 0.2011 - accuracy: 0.93 - ETA: 6s - loss: 0.1597 - accuracy: 0.95 - ETA: 6s - loss: 0.1988 - accuracy: 0.95 - ETA: 6s - loss: 0.1930 - accuracy: 0.95 - ETA: 6s - loss: 0.1828 - accuracy: 0.95 - ETA: 6s - loss: 0.1718 - accuracy: 0.95 - ETA: 6s - loss: 0.1715 - accuracy: 0.96 - ETA: 6s - loss: 0.1702 - accuracy: 0.96 - ETA: 6s - loss: 0.1651 - accuracy: 0.96 - ETA: 6s - loss: 0.1605 - accuracy: 0.96 - ETA: 6s - loss: 0.1540 - accuracy: 0.96 - ETA: 6s - loss: 0.1558 - accuracy: 0.96 - ETA: 6s - loss: 0.1603 - accuracy: 0.96 - ETA: 6s - loss: 0.1656 - accuracy: 0.96 - ETA: 6s - loss: 0.1649 - accuracy: 0.96 - ETA: 6s - loss: 0.1730 - accuracy: 0.96 - ETA: 6s - loss: 0.1796 - accuracy: 0.96 - ETA: 6s - loss: 0.1792 - accuracy: 0.96 - ETA: 6s - loss: 0.1753 - accuracy: 0.96 - ETA: 6s - loss: 0.1731 - accuracy: 0.96 - ETA: 6s - loss: 0.1695 - accuracy: 0.96 - ETA: 6s - loss: 0.1722 - accura

1875/1875 [==============================] - ETA: 0s - loss: 0.0604 - accuracy: 0.96 - ETA: 5s - loss: 0.1468 - accuracy: 0.96 - ETA: 5s - loss: 0.1319 - accuracy: 0.97 - ETA: 5s - loss: 0.1357 - accuracy: 0.97 - ETA: 5s - loss: 0.1197 - accuracy: 0.97 - ETA: 5s - loss: 0.1380 - accuracy: 0.96 - ETA: 5s - loss: 0.1400 - accuracy: 0.96 - ETA: 5s - loss: 0.1376 - accuracy: 0.96 - ETA: 5s - loss: 0.1374 - accuracy: 0.96 - ETA: 5s - loss: 0.1408 - accuracy: 0.96 - ETA: 5s - loss: 0.1397 - accuracy: 0.96 - ETA: 5s - loss: 0.1409 - accuracy: 0.96 - ETA: 5s - loss: 0.1459 - accuracy: 0.96 - ETA: 5s - loss: 0.1454 - accuracy: 0.96 - ETA: 5s - loss: 0.1499 - accuracy: 0.96 - ETA: 5s - loss: 0.1579 - accuracy: 0.96 - ETA: 5s - loss: 0.1639 - accuracy: 0.96 - ETA: 5s - loss: 0.1694 - accuracy: 0.96 - ETA: 5s - loss: 0.1667 - accuracy: 0.96 - ETA: 4s - loss: 0.1654 - accuracy: 0.96 - ETA: 4s - loss: 0.1660 - accuracy: 0.96 - ETA: 4s - loss: 0.1622 - accuracy: 0.96 - ETA: 4s - loss: 0.1593 - accura

KeyboardInterrupt: 

In [98]:
y_n = mynn.expand_labels(y).T

In [99]:
X.shape

(60000, 784)

In [100]:
y_n.shape

(60000, 10)